name: supportship
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.14.0+5
  firebase_database: ^3.1.6



  cupertino_icons: ^0.1.3
  flutter_signin_button: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true
  assets:
    - images/logo3.jpeg

  fonts:
    - family: MuseoModerno
      fonts:
        - asset: fonts/MuseoModerno-VariableFont_wght.ttf

    - family: Sriracha
      fonts:
        - asset: fonts/Sriracha-Regular.ttf
